image: node:18

pipelines:
  default:
    - step:
        name: NPM Install
        script:
          - npm ci
    - step:
        name: Zup Deploy
        # set -o pipefail
        # This way if the deploy fails, we fail before piping to tee.
        script:
          - set -o pipefail
          - npx @zuplo/cli deploy --apiKey "$ZUPLO_API_KEY" | tee
            ./DEPLOYMENT_STDOUT
        artifacts:
          - DEPLOYMENT_STDOUT
    - step:
        name: Zup Test
        script:
          - npx @zuplo/cli test --endpoint $(cat ./DEPLOYMENT_STDOUT |  sed -E
            's/Deployed to (.*)/\1/')
